# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2020
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🧑🏻‍🦽‍➡️"
    subtitle = "究竟要挨多少打才能成角"
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "本文采用 CC BY-NC-SA 4.0 协议许可"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "waline"

    [comments.waline]
        # Prefer HUGO_WALINE_SERVER_URL from the build environment.
        # You can also hard-code your Waline server URL here if you want.
        serverURL      = ""
        lang           = "zh-CN"
        login          = "disable"
        pageSize       = 10
        pageview       = false
        reaction       = false
        search         = false
        wordLimit      = 500
        meta           = ["nick", "mail", "link"]
        requiredMeta   = ["nick", "mail"]
        commentSorting = "oldest"

        [comments.waline.locale]
            admin       = "博主"
            placeholder = "欢迎留言。支持匿名评论，昵称和邮箱为必填。"
